url                          : http://hilary.github.com
title                        : integrating design
subtitle                     : your friendly native guide
author                       : hilary j holz
simple_search                : http://google.com/search
description                  : coding blog by full stack web dev
date_format                  : "ordinal"
subscribe_rss                : /atom.xml
subscribe_email              :
category_feeds               : false
email                        :

root                         : /
permalink                    : /blog/:year/:title/
source                       : source
destination                  : public
plugins                      : plugins
code_dir                     : downloads/code
category_dir                 : blog/categories
markdown                     : kramdown      # default is rdiscount

# default python pygments replaced by pygments.rb, set to true for Albino + Python pygments
pygments                     : false

# pagination is very unpopular (to the point of hatred) with users. 
# Simply limit entries on various pages and offer date and category indexes
index_posts                  : 6
archive_max_posts            : 20

recent_posts                 : 5
excerpt_link                 : "&hellip; read more &hellip;"
excerpt_in_feed              : false
permalink_label              : "permalink"
permalink_label_feed         : "&#9875; permalink"
linklog_marker               : "&rarr;"
linklog_marker_position      : after
linklog_marker_position_feed : after
standard_post_marker         :

titlecase                    : false

# asides
home_aside                 : default.html
blog_index_aside           : index.html
page_aside                 : default.html
post_aside                 : default.html

respectfully_social          : true
twitter_tweet_button         : true
facebook_like                : true
google_plus_one              : true
google_plus_one_size         : small

github_user                  : hilary
github_repo_count            : 3
github_show_profile_link     : false
github_skip_forks            : true

delicious_user               : hilzh
delicious_count              : 3

disqus_short_name            : integrating
disqus_show_comment_count    : false
disqus_developer             : 0

google_plus_user             : holz.hilary@gmail.com
google_plus_image_size       : 16
google_plus_hidden           : false  # doesn't work

# twitter_user                 :
# twitter_tweet_count          : 4
# twitter_show_replies         : false
# twitter_follow_button        : true
# twitter_show_follower_count  : false


