url            : http://hholz.com
title          : integrating design
subtitle       : your friendly native guide
author         : hilary j holz
simple_search  : http://google.com/search
description    : coding blog by full stack web dev
date_format    : "ordinal"

generator_uri  : octoburn/
generator_name : Octoburn

root           : /
source         : source
destination    : public
plugins        : plugins
code_dir       : downloads/code
tag_dir        : tags
markdown       : kramdown
pygments       : false

tag_feeds       : true
feed_dir        : feeds
feed_url        : feeds/integrating_design.xml
excerpt_in_feed : false

permalink       : /blog/:year/:title/
permalink_label : "permalink"
permalink_label_feed : "&#9875; permalink"

index_posts       : 6
excerpt_link      : "[ read me ]"
archive_max_posts : 20

disqus_short_name : integrating

recent_posts         : 5

github_user          : hilary
github_repo_count    : 3
github_skip_forks    : true
github_follow_url    : https://github.com/users/follow?target=      

delicious_user       : hilzh
delicious_count      : 6
delicious_follow_url : https://www.delicious.com/settings/networkedit?action=add&username=

google_plus_user     : holz.hilary@gmail.com
