url                          : http://hilary.github.com
title                        : integrating design
subtitle                     : your friendly native guide
author                       : hilary j holz
simple_search                : http://google.com/search
description                  : coding blog about ruby rails chef vagrant cucumber
date_format                  : "ordinal"
subscribe_rss                : /atom.xml

root                         : /
permalink                    : /blog/:year/:category/:title/
source                       : source
destination                  : public
plugins                      : plugins
code_dir                     : downloads/code
category_dir                 : blog/categories
category_title_prefix        : "Category: "
markdown                     : kramdown
pygments                     : false # default python pygments replaced by pygments.rb

paginate                     : 10    
pagination_dir               : blog  
recent_posts                 : 5     
excerpt_link                 : "read on ..." 
excerpt_in_feed              : false
permalink_label              : "&infin;"
permalink_label_feed         : "&infin; Permalink"
linklog_marker               : "&rarr;"
linklog_marker_position      : after
linklog_marker_position_feed : after
standard_post_marker         :

titlecase                    : false

default_asides : [asides/recent_posts.html, asides/delicious.html, asides/github.html]

# blog_index_asides:
# post_asides:
# page_asides:

github_user              : hilary
github_repo_count        : 3
github_show_profile_link : true
github_skip_forks        : true

delicious_user: hilzh
delicious_count: 3

disqus_short_name: integrating
disqus_show_comment_count: false

facebook_like: false
